module InventoryHelper
  INSTANCE_TYPES = {
    "t2.nano" => { "cores"=> 1, "cpu_speed_ghz"=> "up to 3.3", "ram_gb"=> 0.5, "network"=> "low" },
    "t2.micro" => { "cores"=> 1, "cpu_speed_ghz"=> "up to 3.3", "ram_gb"=> 1, "network"=> "low to moderate" },
    "t2.small" => { "cores"=> 1, "cpu_speed_ghz"=> "up to 3.3", "ram_gb"=> 2, "network"=> "low to moderate" },
    "t2.medium" => { "cores"=> 2, "cpu_speed_ghz"=> "up to 3.3", "ram_gb"=> 4, "network"=> "low to moderate" },
    "t2.large" => { "cores"=> 2, "cpu_speed_ghz"=> "up to 3.0", "ram_gb"=> 8, "network"=> "low to moderate" },
    "m4.large" => { "cores"=> 2, "cpu_speed_ghz"=> "2.4", "ram_gb"=> 8, "network"=> "moderate" },
    "m4.xlarge" => { "cores"=> 4, "cpu_speed_ghz"=> "2.4", "ram_gb"=> 16, "network"=> "high" },
    "m4.2xlarge" => { "cores"=> 8, "cpu_speed_ghz"=> "2.4", "ram_gb"=> 32, "network"=> "high" },
    "m4.4xlarge" => { "cores"=> 16, "cpu_speed_ghz"=> "2.4", "ram_gb"=> 64, "network"=> "high" },
    "m4.10xlarge" => { "cores"=> 40, "cpu_speed_ghz"=> "2.4", "ram_gb"=> 160, "network"=> "10 gigabit" },
    "m3.medium" => { "cores"=> 1, "cpu_speed_ghz"=> "2.5", "ram_gb"=> 3.75, "network"=> "moderate" },
    "m3.large" => { "cores"=> 2, "cpu_speed_ghz"=> "2.5", "ram_gb"=> 7.5, "network"=> "moderate" },
    "m3.xlarge" => { "cores"=> 4, "cpu_speed_ghz"=> "2.5", "ram_gb"=> 15, "network"=> "high" },
    "m3.2xlarge" => { "cores"=> 8, "cpu_speed_ghz"=> "2.5", "ram_gb"=> 30, "network"=> "high" },
    "c4.large" => { "cores"=> 2, "cpu_speed_ghz"=> "2.9", "ram_gb"=> 3.75, "network"=> "moderate" },
    "c4.xlarge" => { "cores"=> 4, "cpu_speed_ghz"=> "2.9", "ram_gb"=> 7.5, "network"=> "high" },
    "c4.2xlarge" => { "cores"=> 8, "cpu_speed_ghz"=> "2.9", "ram_gb"=> 15, "network"=> "high" },
    "c4.4xlarge" => { "cores"=> 16, "cpu_speed_ghz"=> "2.9", "ram_gb"=> 30, "network"=> "high" },
    "c4.8xlarge" => { "cores"=> 36, "cpu_speed_ghz"=> "2.9", "ram_gb"=> 60, "network"=> "10 gigabit" },
    "c3.large" => { "cores"=> 2, "cpu_speed_ghz"=> "2.8", "ram_gb"=> 3.75, "network"=> "moderate" },
    "c3.xlarge" => { "cores"=> 4, "cpu_speed_ghz"=> "2.8", "ram_gb"=> 7.5, "network"=> "moderate" },
    "c3.2xlarge" => { "cores"=> 8, "cpu_speed_ghz"=> "2.8", "ram_gb"=> 15, "network"=> "high" },
    "c3.4xlarge" => { "cores"=> 16, "cpu_speed_ghz"=> "2.8", "ram_gb"=> 30, "network"=> "high" },
    "c3.8xlarge" => { "cores"=> 32, "cpu_speed_ghz"=> "2.8", "ram_gb"=> 60, "network"=> "10 gigabit" },
    "g2.2xlarge" => { "cores"=> 8, "cpu_speed_ghz"=> "2.6", "ram_gb"=> 15, "network"=> "high" },
    "g2.8xlarge" => { "cores"=> 32, "cpu_speed_ghz"=> "2.6", "ram_gb"=> 60, "network"=> "10 gigabit" },
    "x1.32xlarge" => { "cores"=> 128, "cpu_speed_ghz"=> "2.3", "ram_gb"=> 1952, "network"=> "20 gigabit" },
    "r3.large" => { "cores"=> 2, "cpu_speed_ghz"=> "2.5", "ram_gb"=> 15.25, "network"=> "moderate" },
    "r3.xlarge" => { "cores"=> 4, "cpu_speed_ghz"=> "2.5", "ram_gb"=> 30.5, "network"=> "moderate" },
    "r3.2xlarge" => { "cores"=> 8, "cpu_speed_ghz"=> "2.5", "ram_gb"=> 61, "network"=> "high" },
    "r3.4xlarge" => { "cores"=> 16, "cpu_speed_ghz"=> "2.5", "ram_gb"=> 122, "network"=> "high" },
    "r3.8xlarge" => { "cores"=> 32, "cpu_speed_ghz"=> "2.5", "ram_gb"=> 244, "network"=> "10 gigabit" },
    "i2.xlarge" => { "cores"=> 4, "cpu_speed_ghz"=> "2.5", "ram_gb"=> 30.5, "network"=> "moderate" },
    "i2.2xlarge" => { "cores"=> 8, "cpu_speed_ghz"=> "2.5", "ram_gb"=> 61, "network"=> "high" },
    "i2.4xlarge" => { "cores"=> 16, "cpu_speed_ghz"=> "2.5", "ram_gb"=> 122, "network"=> "high" },
    "i2.8xlarge" => { "cores"=> 32, "cpu_speed_ghz"=> "2.5", "ram_gb"=> 244, "network"=> "10 gigabit" },
    "d2.xlarge" => { "cores"=> 4, "cpu_speed_ghz"=> "2.4", "ram_gb"=> 30.5, "network"=> "moderate" },
    "d2.2xlarge" => { "cores"=> 8, "cpu_speed_ghz"=> "2.4", "ram_gb"=> 61, "network"=> "high" },
    "d2.4xlarge" => { "cores"=> 16, "cpu_speed_ghz"=> "2.4", "ram_gb"=> 122, "network"=> "high" },
    "d2.8xlarge" => { "cores"=> 36, "cpu_speed_ghz"=> "2.4", "ram_gb"=> 244, "network"=> "10 gigabit" }
  }
end