server:
  port: 8000

scheduler:
  collect_inventory:
    rake_command: collect_inventory
    interval: 15m
    first_in: 0 # Immediately

  collect_samples:
    rake_command: collect_samples
    interval: 5m
    first_in: 5m

  send_samples:
    rake_command: send_samples
    interval: 15m
    first_in: 15m
