server:
  port: 8000

scheduler:
  collect_inventory:
    rake_command: collect_inventory
    interval: 15m
    first_in: 0 # Immediately

  collect_samples:
    rake_command: collect_samples
    interval: 5m
    first_in: 5m

  send_samples:
    rake_command: send_samples
    interval: 15m
    first_in: 15m

  fetch_price:
    rake_command: fetch_price
    interval: 30d
    first_in: 0 # Immediately

  fetch_detailed_report:
    rake_command: fetch_detailed_report
    interval: 1d
    first_in: 0 # Immediately
