server:
  port: 8000

startup:
  - bootstrap_inventory
  - fetch_price

scheduler:
  fetch_detailed_report:
    rake_command: fetch_detailed_report
    interval: 1d
    first_in: 0

  collect_inventory:
    rake_command: collect_inventory
    interval: 5m
    first_in: 0

  collect_samples:
    rake_command: collect_samples
    interval: 5m
    first_in: 0

  send_samples:
    rake_command: send_samples
    interval: 5m
    first_in: 5m

  fetch_price:
    rake_command: fetch_price
    interval: 30d
    first_in: 30d
