server:
  port: 8000

startup:
  - fetch_price
  - fetch_detailed_report
  - collect_inventory

scheduler:
  collect_inventory:
    rake_command: collect_inventory
    interval: 15m
    first_in: 15m

  collect_samples:
    rake_command: collect_samples
    interval: 5m
    first_in: 0 # Immediately

  send_samples:
    rake_command: send_samples
    interval: 15m
    first_in: 15m

  fetch_price:
    rake_command: fetch_price
    interval: 30d
    first_in: 30d

  fetch_detailed_report:
    rake_command: fetch_detailed_report
    interval: 1d
    first_in: 1d
