server:
  port: 8000

startup:
  - fetch_instance_types
  - bootstrap_inventory
  - fetch_price
  - fetch_detailed_report

scheduler:
  collect_inventory:
    rake_command: collect_inventory
    interval: 5m
    first_in: 5m

  collect_samples:
    rake_command: collect_samples
    interval: 30m
    first_in: 0m

  send_samples:
    rake_command: send_samples
    interval: 30m
    first_in: 35m

  fetch_detailed_report:
    rake_command: fetch_detailed_report
    interval: 1d
    first_in: 1d
    
  fetch_price:
    rake_command: fetch_price
    interval: 30d
    first_in: 30d

  fetch_instance_types:
    rake_command: fetch_instance_types
    interval: 1d
    first_in: 1d